name: 'Build all Java Versions'
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version-file: '.java-version'
          distribution: 'adopt'
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: setup-java-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            setup-java-${{ runner.os }}-maven-
            setup-java-
      - name: Maven Install
        run: mvn clean install
  test-java-7-spring-boot-1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 7
        uses: actions/setup-java@v1
        with:
          java-version: 7
      - uses: actions/cache/restore@v3
        with:
          path: ~/.m2/repository
          key: setup-java-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            setup-java-${{ runner.os }}-maven-
            setup-java-
      - name: Maven Verify
        run: cd smt-waiting-test && mvn clean verify -Pjava7 -Pspring-boot1
  test-java-spring-boot:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java: '8'
            spring-boot: '1'
          - java: '8'
            spring-boot: '2'
          - java: '11'
            spring-boot: '2'
          - java: '17'
            spring-boot: '2'
          - java: '17'
            spring-boot: '3'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - uses: actions/cache/restore@v3
        with:
          path: ~/.m2/repository
          key: setup-java-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            setup-java-${{ runner.os }}-maven-
            setup-java-
      - name: Maven Verify
        run: cd smt-waiting-test && mvn clean verify -Pjava${{ matrix.java }} -Pspring-boot${{ matrix.spring-boot }}